### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by JIN-Li-stats** [blog-neas/INAr#1]
When I install this package, there is an error: 

>    ERROR: package installation failed
> Error: Failed to install 'INAr' from GitHub:
>   ! System command 'Rcmd.exe' failed
> In addition: Warning messages:
> 1: package ‘Biobase’ is not available for this version of R

Therefore, I would like to know which version of R this package is based on.

The version of R running on my computer:
> system: Windows11
> R version: 4.2.1

**Comment by blog-neas** [comment]
Hi,
there may be several reasons that cause the Rcmd.exe fail error. The R version I am using to develop the package is 4.2.1 and I run it smoothly either on Win10/Win11 or Ubuntu, I am still testing how the package works on Mac OS but as far as I know there should be no big issues. So, I don't think that the OS and the version of R are the problem here.
First of all, try to use "remotes::install_github()" instead of "devtools::install_github()".
In addition, the warning issue is due to an upstream dependency, called _Biobase_, that is not listed on CRAN but in _Bioconductor_. To get rid of the warning I suggest you to install this package in advance using the following code:

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biobase")
```

In future versions I will figure out if it's possible to avoid to load this specific package since it has no direct use in INAr.

**Comment by JIN-Li-stats** [comment]
Thanks for your reply.
